#############################################################################
# Makefile for building: DBppGuiDev
# Generated by qmake (3.1) (Qt 5.12.12)
# Project:  DBppGuiDev.pro
# Template: subdirs
# Command: E:\Qt5\5.12.12\msvc2017_64\bin\qmake.exe -o Makefile DBppGuiDev.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = E:\Qt5\5.12.12\msvc2017_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = E:\Qt5\5.12.12\msvc2017_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = E:\Qt5\5.12.12\msvc2017_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-DBppGuiAppl15 \
		sub-DamBreakAPI \
		sub-DamBreakVisualDbg


sub-DBppGuiAppl15-qmake_all:  FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	cd DBppGuiAppl15\ && $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && $(MAKE) -f Makefile qmake_all
sub-DBppGuiAppl15: $(MAKEFILE) FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-DBppGuiAppl15-make_first: FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-DBppGuiAppl15-all: FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-DBppGuiAppl15-clean: FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-DBppGuiAppl15-distclean: FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-DBppGuiAppl15-install_subtargets: FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-DBppGuiAppl15-uninstall_subtargets: FORCE
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-DamBreakAPI-qmake_all:  FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	cd DamBreakAPI\ && $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && $(MAKE) -f Makefile qmake_all
sub-DamBreakAPI: $(MAKEFILE) FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-DamBreakAPI-make_first: FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-DamBreakAPI-all: FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-DamBreakAPI-clean: FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-DamBreakAPI-distclean: FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-DamBreakAPI-install_subtargets: FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-DamBreakAPI-uninstall_subtargets: FORCE
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-DamBreakVisualDbg-qmake_all:  FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	cd DamBreakVisualDbg\ && $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && $(MAKE) -f Makefile qmake_all
sub-DamBreakVisualDbg: $(MAKEFILE) FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-DamBreakVisualDbg-make_first: FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-DamBreakVisualDbg-all: FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-DamBreakVisualDbg-clean: FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-DamBreakVisualDbg-distclean: FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-DamBreakVisualDbg-install_subtargets: FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-DamBreakVisualDbg-uninstall_subtargets: FORCE
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: DBppGuiDev.pro ..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\win32-msvc\qmake.conf ..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\spec_pre.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\angle.conf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\windows-vulkan.conf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\msvc-desktop.conf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\qconfig.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_location.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qt_functions.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qt_config.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\win32-msvc\qmake.conf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\msvc-version.conf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\toolchain.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\default_pre.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\resolve_config.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\default_post.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qml_debug.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\precompile_header.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\warn_on.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qmake_use.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\file_copies.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\win32\windows.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\testcase_targets.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\exceptions.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\yacc.prf \
		..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\lex.prf \
		DBppGuiDev.pro
	$(QMAKE) -o Makefile DBppGuiDev.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\spec_pre.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\angle.conf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\windows-vulkan.conf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\msvc-desktop.conf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\qconfig.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_charts.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_location.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_purchasing.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webengine.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webview.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qt_functions.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qt_config.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\win32-msvc\qmake.conf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\exclusive_builds.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\common\msvc-version.conf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\toolchain.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\default_pre.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\win32\default_pre.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\resolve_config.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\default_post.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qml_debug.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\precompile_header.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\warn_on.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\qmake_use.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\file_copies.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\win32\windows.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\testcase_targets.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\exceptions.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\yacc.prf:
..\..\..\Qt5\5.12.12\msvc2017_64\mkspecs\features\lex.prf:
DBppGuiDev.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile DBppGuiDev.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-DBppGuiAppl15-qmake_all sub-DamBreakAPI-qmake_all sub-DamBreakVisualDbg-qmake_all FORCE

make_first: sub-DBppGuiAppl15-make_first sub-DamBreakAPI-make_first sub-DamBreakVisualDbg-make_first  FORCE
all: sub-DBppGuiAppl15-all sub-DamBreakAPI-all sub-DamBreakVisualDbg-all  FORCE
clean: sub-DBppGuiAppl15-clean sub-DamBreakAPI-clean sub-DamBreakVisualDbg-clean  FORCE
distclean: sub-DBppGuiAppl15-distclean sub-DamBreakAPI-distclean sub-DamBreakVisualDbg-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-DBppGuiAppl15-install_subtargets sub-DamBreakAPI-install_subtargets sub-DamBreakVisualDbg-install_subtargets FORCE
uninstall_subtargets: sub-DBppGuiAppl15-uninstall_subtargets sub-DamBreakAPI-uninstall_subtargets sub-DamBreakVisualDbg-uninstall_subtargets FORCE

sub-DBppGuiAppl15-debug:
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-DamBreakAPI-debug:
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-DamBreakVisualDbg-debug:
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-DBppGuiAppl15-debug sub-DamBreakAPI-debug sub-DamBreakVisualDbg-debug

sub-DBppGuiAppl15-release:
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-DamBreakAPI-release:
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-DamBreakVisualDbg-release:
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-DBppGuiAppl15-release sub-DamBreakAPI-release sub-DamBreakVisualDbg-release

sub-DBppGuiAppl15-check:
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-DamBreakAPI-check:
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-DamBreakVisualDbg-check:
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-DBppGuiAppl15-check sub-DamBreakAPI-check sub-DamBreakVisualDbg-check

sub-DBppGuiAppl15-benchmark:
	@if not exist DBppGuiAppl15\ mkdir DBppGuiAppl15\ & if not exist DBppGuiAppl15\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DBppGuiAppl15\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DBppGuiAppl15\DBppGuiAppl15.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-DamBreakAPI-benchmark:
	@if not exist DamBreakAPI\ mkdir DamBreakAPI\ & if not exist DamBreakAPI\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakAPI\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakAPI\DamBreakAPI.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-DamBreakVisualDbg-benchmark:
	@if not exist DamBreakVisualDbg\ mkdir DamBreakVisualDbg\ & if not exist DamBreakVisualDbg\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd DamBreakVisualDbg\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\QtProjects\DamBreakppGUI\DBppGuiDev\DamBreakVisualDbg\DamBreakVisualDbg.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-DBppGuiAppl15-benchmark sub-DamBreakAPI-benchmark sub-DamBreakVisualDbg-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

